#!/usr/bin/env python3
"""Phase 4: Replace auto-journal with trade confirmation via TG inline keyboard."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from apply_text_patch import apply_patches

FILE = os.path.join(os.path.dirname(__file__), "..", "..", "server.py")

patches = [
    # 1. Replace auto-journal + broken tg_send with inline keyboard confirmation
    (
        '    # Auto-log trade in journal\n'
        '    if status_code == 200 and response.get("ok") and JOURNAL_OK:\n'
        '        try:\n'
        '            _sig = payload.get("signal", "").lower()\n'
        '            _ticker = payload.get("ticker", "")\n'
        '            _price = float(payload.get("price", 0)) if payload.get("price") else 0\n'
        '            _strat = payload.get("strategy", payload.get("strategy_name", "TV Alert"))\n'
        '            _qty = int(payload.get("quantity", 0)) if payload.get("quantity") else 0\n'
        '            if _sig in ("buy", "entry", "long"):\n'
        '                _tid = open_trade(\n'
        '                    symbol=_ticker, entry_price=_price, quantity=_qty,\n'
        '                    entry_reason=f"TradingView: {payload.get(\'message\', _sig)}",\n'
        '                    strategy=_strat, entry_signal_id=response.get("saved_id"),\n'
        '                )\n'
        '                logger.info(f"TV auto-journal: opened trade #{_tid} for {_ticker}")\n'
        '            elif _sig in ("sell", "exit", "close", "short"):\n'
        '                _open = get_open_trades()\n'
        '                _match = [t for t in _open if t["symbol"].upper() == _ticker.upper()]\n'
        '                if _match:\n'
        '                    close_trade(_match[0]["id"], _price, exit_reason=f"TradingView: {_sig}")\n'
        '                    logger.info(f"TV auto-journal: closed trade #{_match[0][\'id\']} for {_ticker}")\n'
        '        except Exception as _je:\n'
        '            logger.warning(f"TV auto-journal error: {_je}")\n'
        '    # Send TG alert if successful\n'
        '    if status_code == 200 and response.get("ok") and response.get("tg_message"):\n'
        '        try:\n'
        '            saved_id = response.get("saved_id")\n'
        '            await tg_send(response["tg_message"])\n'
        '            if saved_id:\n'
        '                mark_telegram_sent(saved_id)\n'
        '        except Exception as e:\n'
        '            logger.error(f"TV TG send error: {e}")',

        '    # Send trade confirmation via TG inline keyboard\n'
        '    if status_code == 200 and response.get("ok"):\n'
        '        try:\n'
        '            _sig = payload.get("signal", "").lower()\n'
        '            _ticker = payload.get("ticker", "")\n'
        '            _price = payload.get("price", "0")\n'
        '            _strat = payload.get("strategy", payload.get("strategy_name", "TV Alert"))\n'
        '            _qty = payload.get("quantity", "0")\n'
        '            _msg_text = response.get("tg_message", "")\n'
        '            saved_id = response.get("saved_id", "")\n'
        '            if _sig in ("buy", "entry", "long", "sell", "exit", "close", "short"):\n'
        '                _action = "buy" if _sig in ("buy", "entry", "long") else "sell"\n'
        '                _cb_data = f"{_ticker}|{_price}|{_action}|{_strat}|{_qty}|{saved_id}"\n'
        '                _confirm_msg = _msg_text or f"\\U0001f4e1 TV Signal: {_action.upper()} {_ticker} @ {_price}"\n'
        '                _confirm_msg += f"\\n\\n\\u0634\\u0631\\u064a\\u062a \\u0648\\u0644\\u0627 \\u062a\\u062c\\u0627\\u0647\\u0644\\u062a\\u061f"\n'
        '                _btns = [\n'
        '                    {"text": "\\u0634\\u0631\\u064a\\u062a \\u2705", "callback_data": f"trade_confirm:{_cb_data}"},\n'
        '                    {"text": "\\u062a\\u062c\\u0627\\u0647\\u0644\\u062a \\u274c", "callback_data": f"trade_skip:{_cb_data}"},\n'
        '                ]\n'
        '                admin_id = get_admin_chat_id() if TG_OPS_OK else None\n'
        '                if not admin_id:\n'
        '                    _aid_path = os.path.join(os.path.dirname(__file__) or ".", "data", "admin_chat_id.txt")\n'
        '                    if os.path.exists(_aid_path):\n'
        '                        admin_id = open(_aid_path).read().strip()\n'
        '                if admin_id:\n'
        '                    await tg_send_inline(int(admin_id), _confirm_msg, _btns, columns=2)\n'
        '                    if saved_id:\n'
        '                        mark_telegram_sent(saved_id)\n'
        '                    logger.info(f"TV trade confirmation sent: {_action} {_ticker} @ {_price}")\n'
        '                else:\n'
        '                    logger.warning("TV trade confirmation: no admin chat_id found")\n'
        '            elif _msg_text:\n'
        '                # Non-trade signals (info, alert) — send plain message\n'
        '                admin_id = get_admin_chat_id() if TG_OPS_OK else None\n'
        '                if not admin_id:\n'
        '                    _aid_path = os.path.join(os.path.dirname(__file__) or ".", "data", "admin_chat_id.txt")\n'
        '                    if os.path.exists(_aid_path):\n'
        '                        admin_id = open(_aid_path).read().strip()\n'
        '                if admin_id:\n'
        '                    await tg_send(int(admin_id), _msg_text)\n'
        '                    if saved_id:\n'
        '                        mark_telegram_sent(saved_id)\n'
        '        except Exception as e:\n'
        '            logger.error(f"TV TG send error: {e}")',
    ),

    # 2. Add trade_confirm: and trade_skip: handlers in callback query handler
    (
        '    elif data.startswith("cmd:"):\n'
        '        sub = "/" + data[4:]\n'
        '        r = await tg_handle_command(chat_id, sub)\n'
        '        if r and r != "__inline_sent__":\n'
        '            await tg_send(chat_id, r)\n'
        '        answer = ""',

        '    elif data.startswith("trade_confirm:"):\n'
        '        # User confirmed they took the trade\n'
        '        _td = data[len("trade_confirm:"):].split("|")\n'
        '        if len(_td) >= 5 and JOURNAL_OK:\n'
        '            _tc_sym, _tc_price, _tc_action, _tc_strat, _tc_qty = _td[0], _td[1], _td[2], _td[3], _td[4]\n'
        '            _tc_saved = _td[5] if len(_td) > 5 else ""\n'
        '            try:\n'
        '                _tc_price_f = float(_tc_price) if _tc_price else 0\n'
        '                _tc_qty_i = int(_tc_qty) if _tc_qty and _tc_qty != "0" else 0\n'
        '                if _tc_action == "buy":\n'
        '                    _tc_tid = open_trade(\n'
        '                        symbol=_tc_sym, entry_price=_tc_price_f, quantity=_tc_qty_i,\n'
        '                        entry_reason=f"TradingView (confirmed)",\n'
        '                        strategy=_tc_strat, entry_signal_id=_tc_saved or None,\n'
        '                    )\n'
        '                    await tg_send(chat_id, f"\\u2705 \\u062a\\u0645 \\u062a\\u0633\\u062c\\u064a\\u0644 \\u0634\\u0631\\u0627\\u0621 {_tc_sym} @ {_tc_price} (#{_tc_tid})")\n'
        '                    logger.info(f"Trade confirmed: BUY {_tc_sym} @ {_tc_price} tid={_tc_tid}")\n'
        '                elif _tc_action == "sell":\n'
        '                    _tc_open = get_open_trades()\n'
        '                    _tc_match = [t for t in _tc_open if t["symbol"].upper() == _tc_sym.upper()]\n'
        '                    if _tc_match:\n'
        '                        close_trade(_tc_match[0]["id"], _tc_price_f, exit_reason="TradingView (confirmed)")\n'
        '                        await tg_send(chat_id, f"\\u2705 \\u062a\\u0645 \\u0625\\u063a\\u0644\\u0627\\u0642 {_tc_sym} @ {_tc_price}")\n'
        '                        logger.info(f"Trade confirmed: SELL {_tc_sym} @ {_tc_price}")\n'
        '                    else:\n'
        '                        await tg_send(chat_id, f"\\u26a0\\ufe0f \\u0645\\u0627 \\u0641\\u064a\\u0647 \\u0635\\u0641\\u0642\\u0629 \\u0645\\u0641\\u062a\\u0648\\u062d\\u0629 \\u0644\\u0640 {_tc_sym}")\n'
        '                answer = "\\u2705"\n'
        '            except Exception as _tc_e:\n'
        '                logger.error(f"Trade confirm error: {_tc_e}")\n'
        '                await tg_send(chat_id, f"\\u274c \\u062e\\u0637\\u0623: {str(_tc_e)[:100]}")\n'
        '                answer = "\\u274c"\n'
        '        else:\n'
        '            answer = "Journal not loaded"\n'
        '\n'
        '    elif data.startswith("trade_skip:"):\n'
        '        # User skipped/ignored the trade signal\n'
        '        _ts = data[len("trade_skip:"):].split("|")\n'
        '        _ts_sym = _ts[0] if _ts else "?"\n'
        '        _ts_action = _ts[2] if len(_ts) > 2 else "?"\n'
        '        _ts_price = _ts[1] if len(_ts) > 1 else "?"\n'
        '        logger.info(f"Trade skipped: {_ts_action} {_ts_sym} @ {_ts_price}")\n'
        '        await tg_send(chat_id, f"\\u274c \\u062a\\u0645 \\u062a\\u062c\\u0627\\u0647\\u0644 \\u0625\\u0634\\u0627\\u0631\\u0629 {_ts_sym}")\n'
        '        answer = "\\u274c"\n'
        '\n'
        '    elif data.startswith("cmd:"):\n'
        '        sub = "/" + data[4:]\n'
        '        r = await tg_handle_command(chat_id, sub)\n'
        '        if r and r != "__inline_sent__":\n'
        '            await tg_send(chat_id, r)\n'
        '        answer = ""',
    ),
]

result = apply_patches(FILE, patches)
import json
print(json.dumps(result.to_dict(), indent=2, ensure_ascii=False))
